# Name and metadata of your task
task_name: 'AssholeInChief'
author: 'AIC'
description: 'We choose an asshole, and we troll them!!!!'
repositoryUrl: 'https://github.com/chaollapark/SecretProject/'
imageUrl: 'https://ipfs-gateway.koii.live/ipfs/bafybeifivizbh4chl4qzcva7gwezdvcqejfz4erqn3aec2ipgjwke5p3eq/JDVcouch.jpg'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 15075000

audit_window: 5000
submission_window: 5000

# Amounts in KOII
minimum_stake_amount: 1.9

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 10

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 5

#Space in MBs for the account size, that holds the task data
space: 5

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: TASK_VARIABLE
    value: 'TWITTER_USERNAME'
    description: 'The username of your volunteer Twitter account. Please ensure your volunteer Twitter account has passed the Twitter verification process.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PHONE'
    description: 'If verification is required, will use your phone number to login.'
  - type: TASK_VARIABLE
    value: 'TWITTER_COMMENTS'
    description: 'Add the comments you need to post on Twitter.'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: ''

# Provide the description for changes made in new version of task
migrationDescription: ''
# - type: TASK_VARIABLE
#   value: 'TWITTER_PROFILE'
#   description: 'User name of the profile where you need to post the comment.'
